# Generated by Django 4.0.3 on 2022-04-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField()),
                ('totalOrders', models.IntegerField(default=0)),
                ('totalVisitors', models.IntegerField(default=0)),
                ('totalRevenue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.CharField(max_length=50)),
                ('visitingTime', models.DateTimeField()),
            ],
        ),
    ]
