# Generated by Django 4.0.3 on 2022-05-04 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('redirection_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageCountryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('percent_users', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MajorPaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('percent_users', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StoreManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_address', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=100)),
                ('payment_gateway', models.CharField(max_length=100)),
                ('shipment_partner', models.CharField(max_length=100)),
                ('is_international', models.BooleanField(default=False)),
                ('domain_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_service_provider', to='goglocal_store.domainserviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_management_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlocalStoreHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_country_relation', to='goglocal_store.languagecountryrelation')),
                ('payment_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateway', to='goglocal_store.majorpaymentgateway')),
            ],
        ),
    ]
