# Generated by Django 4.0.3 on 2022-05-11 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SetupDigitalPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_of_the_product_you_sell', models.CharField(max_length=100)),
                ('brand_plans_for_future', models.CharField(max_length=100)),
                ('which_digital_marketing_activities_your_company_does', models.CharField(max_length=200)),
                ('keywords_you_have_identified', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_digital_push_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('total_price', models.IntegerField(default=0)),
                ('services', models.ManyToManyField(related_name='services', to='digital_push.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_service_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
