# Generated by Django 4.0.3 on 2022-05-16 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='onboarding/categories/')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('option', models.CharField(max_length=1000)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingQuestionCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order_no', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('order_no', models.IntegerField(default=0)),
                ('question', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='onboarding/questions/')),
                ('category_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_question', to='onboarding.onboardingquestioncategories')),
                ('options', models.ManyToManyField(related_name='options', to='onboarding.onboardingoptions')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.ManyToManyField(blank=True, related_name='onboarding_answers_answer', to='onboarding.onboardingoptions')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_answers_question', to='onboarding.onboardingquestions')),
            ],
        ),
    ]
