# Generated by Django 4.0.3 on 2022-05-16 12:32

from django.db import migrations

from uuid import uuid4



categories = [
    'Fashion',
    'Electronics',
    'Home',
    'Food',
    'Beauty',
    'Others'
]

category_images = []

question_categories = [
    'general',
    'global_ecommerce_store',
    'going_global_strategy_and_digital_push',
    'access_to_the_world',
    'global_ecommerce_fullfilment',
    'cross_border_trade_compliance',
    'international_finance',
    'b2b_sourcing',
]

category_wise_questions = []


t1 = [
    'Do you have sales via eCommerce ?',
    'Do you have a partner who helps you strategize eCommerce sales and marketing?',
    'Do you get international orders?',
    'Do you have an international payments partner?',
    'Do you have a logistic partner that fulfills your international orders?',
    'Which technologies have you incorporated into your operations (choose all that apply)?',
]

t1o = [
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]],
    [['CMS', True], ['OMS', True], ['WMS', True], ['Other', True]]
]

t2 = [
    '(A) Do you have a ‘.com’ eCommerce store?',
    '(B) Do you get international orders through your eCommerce store?',
    '(C) Are you able to change your eCommerce store’s content and currency based on the geography of the international visitor?'
]

t2o = [
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]]
]

t3 = [
    '(A) Do you have a global presence?',
    '(B) Are you able to target the right international markets based on your product category’s data-driven insights?',
    '(C) Do you push your eCommerce store digitally in international channels?'
]

t3o = [
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]]
]

t4 = [
    '(A) Are your products listed on any domestic marketplaces like Amazon.in, flipkart.in, etc.?',
    '(B) Are your products listed on any international marketplaces like Amazon.com, ebay.com, etc.?',
    '(C) Do you have a partner assisting you in listing your products on marketplaces?'
]

t4o = [
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]]
]

t5 = [
    '(A) Does it take more than 1 week to fulfil international orders?',
    '(B) Do you store your goods outside India to fulfil international orders?',
    '(C) Do you offer returns to international customers? (Y/N)'
]

t5o = [
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]]
]

t6 = [
    '(A) Have you hired service providers for international trade compliance adherence?',
    '(B) Do your international customers have to pay the local duties/VAT at the time of order collection?',
    '(C) Have your international orders been delayed due to barriers in custom clearance?'
]

t6o = [
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]]
]

t7 = [
    '(A) Do you think you pay high commissions/charges for receiving payments in foreign currency?',
    '(B) Do you have access to collateral free working capital based on your export invoices?',
    '(C) Do you have access to international transit insurance?'
]

t7o = [
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]]
]

t8 = [
    '(A) Do you have an efficient digital cataloging service in place?',
    '(B) Do you sell your products in bulk globally?',
    '(C) Are your products listed on any global B2B marketplaces?',
]

t8o = [
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]],
    [['Yes', True], ['No', False]]
]


def add_question(apps, schema_editor):

    OnboardingCategories = apps.get_model('onboarding', 'OnboardingCategories')
    OnboardingQuestionCategories = apps.get_model('onboarding', 'OnboardingQuestionCategories')
    OnboardingOptions = apps.get_model('onboarding', 'OnboardingOptions')
    OnboardingQuestions = apps.get_model('onboarding', 'OnboardingQuestions')

    for category in categories:
        OnboardingCategories.objects.create(name=category, image='/media/onboarding/categories/test.png')

    category_wise_questions.append([t1, t1o])
    category_wise_questions.append([t2, t2o])
    category_wise_questions.append([t3, t3o])
    category_wise_questions.append([t4, t4o])
    category_wise_questions.append([t5, t5o])
    category_wise_questions.append([t6, t6o])
    category_wise_questions.append([t7, t7o])
    category_wise_questions.append([t8, t8o])


    for i in range(len(question_categories)):
        question_cat = OnboardingQuestionCategories(name=question_categories[i], order_no=i+1)
        question_cat.save()

        questions = category_wise_questions[i]

        for i in range(len(questions[0])):
            question_statement = questions[0][i]
            options = questions[1][i]


            qn = OnboardingQuestions(uuid=str(uuid4()), question=question_statement, order_no=i+1, category_question=question_cat, image='/media/onboarding/categories/test.png')
            qn.save()

            for option in options:
                optn = OnboardingOptions(uuid=str(uuid4()), option=option[0], is_correct=option[1])
                optn.save()

                qn.options.add(optn)

            qn.save()
    


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_question),
    ]
