# Generated by Django 4.0.3 on 2022-05-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('file_field', models.FileField(upload_to='support_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('is_resolved', models.BooleanField(default=False)),
                ('attachments', models.ManyToManyField(related_name='support_files', to='support.supportfiles')),
            ],
        ),
    ]
